### ISSUE TITLE
can't work, either.

### ISSUE THREAD

**Issue by underattraction** [chatziko/location-guard#7]
The icon never shows, and fixed location setting can't work either.
![capture2](https://cloud.githubusercontent.com/assets/11501878/6665571/fcc3a1bc-cc15-11e4-8730-1c03b0536b31.jpg)
![capture](https://cloud.githubusercontent.com/assets/11501878/6665572/fccde8ca-cc15-11e4-945c-be664e8deed5.jpg)
I am using winXP(SP3)+firefox 36.0.1

**Comment by chatziko** [comment]
Hello and thanks for your report.

Could you please do the following to help us debug the problem:
1. open the options page (screenshot 1)
2. open the web console by pressing Control-Shift-K
3. refresh the page until the problem in your screenshot 1 appears
4. copy-paste all contents of the web console.

Thanks.

**Comment by underattraction** [comment]
Hi, chatziko:
here comes the console message:
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
ReferenceError: extension is not defined browser.js:144:2
已棄用 getPreventDefault()。請改用 defaultPrevented。 jquery.min.js:5:0
![capture3](https://cloud.githubusercontent.com/assets/11501878/6679565/58dffb4e-cc84-11e4-9724-e81eed989828.jpg)

**Comment by underattraction** [comment]
Hi, chatziko:
here comes the console message:
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
ReferenceError: extension is not defined browser.js:144:2
已棄用 getPreventDefault()。請改用 defaultPrevented。 jquery.min.js:5:0
![capture3](https://cloud.githubusercontent.com/assets/11501878/6682797/713334d4-ccb8-11e4-9730-ce9341714fdf.jpg)

**Comment by chatziko** [comment]
Thanks again for the help!
Can you also send me the contents of the browser console:

1. open a fresh browser (no tabs)
2. press Control-Shift-J to open the browser console
3. open Location Guard's options page, refresh until the problem appears
4. copy-paste all contents of the browser console.

Thanks!

**Comment by underattraction** [comment]
Hi, chatziko:
It's the same message:
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
ReferenceError: extension is not defined browser.js:144:2
已棄用 getPreventDefault()。請改用 defaultPrevented。 jquery.min.js:5:0

**Comment by chatziko** [comment]
Hello, still can't understand what's going on :(

One last thing:
1. Download the "location-guard.xpi" file from [this link](https://drive.google.com/open?id=0B0HBCTaW5FwHaGNTOTFZdl9Db0k&authuser=0)
2. Remove Location Guard and restart Firefox
3. Open the browser console by pressing Control-Shift-J (**not K**) and press "Clear". Leave the console open.
4. Drag&drop "location-guard.xpi" in the main firefox window. A dialog will appear, press "Install Now"
5. Go to the options page, refresh until the problem appears
6. Copy-paste all contents of the browser console. It should look like the attached image.

Thanks again for your help!


![browser_console](https://cloud.githubusercontent.com/assets/362089/6736605/30eeb77c-ce66-11e4-9ffc-130437bb8217.png)

**Comment by chatziko** [comment]
Hello again,

we just released a new version 1.2.0 of Location Guard in which much of the Firefox code has been rewritten.

It's likely that this version fixes your problem, could you please upgrade to 1.2.0 and give it a try?
https://addons.mozilla.org/en-US/firefox/addon/location-guard/

Thanks a lot in advance for your help!

**Comment by underattraction** [comment]
![capture](https://cloud.githubusercontent.com/assets/11501878/7059205/8ef7385a-de9f-11e4-8d3b-bc9ac16a570d.jpg)
Still can't work...

**Comment by chatziko** [comment]
Thanks again for your help. Could you please do the following:

1. Download the "location-guard.xpi" file from [this link](https://drive.google.com/open?id=0B0HBCTaW5FwHaGNTOTFZdl9Db0k&authuser=0)
(the link should work now)
2. Remove Location Guard and restart Firefox
3. Open the browser console by pressing Control-Shift-J (**not K**) and press "Clear". Leave the console open.
4. Drag&drop "location-guard.xpi" in the main firefox window. A dialog will appear, press "Install Now"
5. Go to the options page, refresh until the problem appears
6. Copy-paste all contents of the browser console. It should look like the attached image.

**Comment by underattraction** [comment]
![capture](https://cloud.githubusercontent.com/assets/11501878/7080635/0e7a6c14-df68-11e4-9256-b8c387e9c573.jpg)
can't work still...

**Comment by chatziko** [comment]
Hello again, unfortunately I cannot reproduce the problem :(

The only way I can see to further debug the issue would be to give me remote access to your PC using Chrome Remote Desktop, which is free and very easy to use.
 * you can [download it here](https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp?hl=en) (you need to use Google Chrome for this)
 * you run it and select "Share", this generates a code that I can use to access your PC
 * of course you can see what I'm doing and you can always stop sharing at any moment

If you're interested is trying this let me know at what times you're available.

Thanks again for your help!

**Comment by MajorLunaC** [comment]
I have the same problem on Slackware Linux, Firefox ESR 38.4.0 . The location button (arrow) does not trigger sharing of location bar in the demo, but it DOES work when viewing the Privacy Levels map.

The Fixed Location map never shows. I can provide any of the info above if you like.

The settings never change, no matter what I try. How are they stored? I try to keep my browser as private as possible, so most everything is deleted on close of Firefox or never kept (pass, and such). Can there be an alternate interface?

**Comment by chatziko** [comment]
The problem with this bug is that so far I haven't been able to reproduce it :(
Any chance you could reproduce it in a virtualbox image and send me the whole image?

**Comment by chatziko** [comment]
This issue is older than a year, concerns an old version of the addon and could not be reproduced.

I'm closing it for now. Feel free to re-open if you can reproduce it with the latest version.
